[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = {path="../shared"}
futures = "0.3.31"
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
